name: Update resources
on:
  workflow_dispatch: 
  schedule:
    - cron: 5 4 2,16 * *
jobs:
  build:
    name: Update resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm clean-install
      - name: Download resources
        run: node scripts/downloadResources.js
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update new resources (${{ github.run_number }})'
          pathspec_error_handling: ignore
